# Generated by Django 5.2.9 on 2025-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='Food', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kk',
            field=models.CharField(default='Food', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(default='Food', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='life_en',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='life_kk',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='life_ru',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kk',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_en',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_kk',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_ru',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
    ]
